# -*- coding: utf-8 -*-
"""KNN_regression.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1Bg1K5X1M_kMVal-u3bVJk2FWao6Cql7o
"""

from google.colab import drive
drive.mount('/content/gdrive')

from numpy import genfromtxt
data_path = '/content/gdrive/MyDrive/KNN/diabetes.csv'
my_data = genfromtxt(data_path, delimiter=',')

#my_data.shape
type(my_data)

data = my_data.tolist()
for i in range(5):
  print(data[i])
type(data)

import numpy as np
import random
import math

Train_set = []
Val_set = [] 
Test_set = []
random.shuffle(data)
for S in data:
  R = random.uniform(0, 1)
  if R>=0 and R<=0.7:
   Train_set.append(S)
  elif R>0.7 and R<=0.85:
   Val_set.append(S)
  else:
   Test_set.append(S)

def average(l,k):
    l = l[:k]
    sum = 0
    for i in range(k):
        sum += l[i][1]
        

    return sum/k

def knn_regression(data,Train_set,Val_set,Test_set):
  k=5
  error = 0
  v_count = 0
  for v in Val_set:
    count = 0
    count1 = 0
    count2 = 0
    l = []
    for t in Train_set:
      a = np.array(v[:10])
      b = np.array(t[:10])
      distance = np.linalg.norm(a-b)
      tmp = [distance,t[-1]]
      l.append(tmp)
    l.sort()
    avg = average(l,k)
    error = error+(v[-1]-avg)**2
    v_count+=1
  Mean_Squared_Error = error/v_count
  print(Mean_Squared_Error)
   
knn_regression(data,Train_set,Val_set,Test_set)